#### function to extract data from binance api

In [1]:
from binance.client import Client
import pandas as pd
def data_extract(sym, start, end):
    client = Client('API_KEY', 'SECRET_KEY')
    if end =="":
        cryptocurrency = client.get_historical_klines(symbol=sym, interval=Client.KLINE_INTERVAL_1HOUR, start_str=start)
    else:
        cryptocurrency = client.get_historical_klines(symbol=sym, interval=Client.KLINE_INTERVAL_1HOUR, start_str=start, end_str=end)
    cryptocurrency = pd.DataFrame(cryptocurrency, columns=['Open time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Close time', 'Quote asset volume', 'Number of trades', 'Taker buy base asset volume', 'Taker buy quote asset volume', 'Ignore'])
    return cryptocurrency

In [2]:
symbol = 'BTCUSDT'
start = '2020-02-13 20:00:00'
end = '2022-05-30 19:00:00'
btcDf = data_extract(symbol,start,end)

In [3]:
btcDf

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
0,1581624000000,10251.15000000,10265.00000000,10208.14000000,10226.61000000,1110.87648000,1581627599999,11367943.05473027,18443,536.35186100,5488846.64546319,0
1,1581627600000,10226.50000000,10228.95000000,10181.88000000,10189.01000000,1675.43181400,1581631199999,17094297.66986849,25854,940.36388200,9595324.40257100,0
2,1581631200000,10189.86000000,10240.26000000,10185.03000000,10224.15000000,972.47001000,1581634799999,9935367.69479534,18466,473.08451800,4833198.44347059,0
3,1581634800000,10224.00000000,10252.79000000,10207.02000000,10229.63000000,1056.26183300,1581638399999,10810760.00926639,18802,537.16419900,5498374.28798722,0
4,1581638400000,10227.78000000,10242.79000000,10178.27000000,10224.81000000,1699.63463700,1581641999999,17342306.13161787,26080,881.95213800,8999489.16933570,0
...,...,...,...,...,...,...,...,...,...,...,...,...
20054,1653922800000,30467.42000000,30679.00000000,30450.00000000,30634.08000000,1933.56178000,1653926399999,59107573.44589040,38164,996.18116000,30458267.97028950,0
20055,1653926400000,30634.08000000,30714.22000000,30566.54000000,30622.04000000,1908.30848000,1653929999999,58467651.43692040,41731,860.87346000,26378447.12552660,0
20056,1653930000000,30622.04000000,30786.49000000,30582.70000000,30706.84000000,1788.90178000,1653933599999,54923611.55275110,34868,990.22368000,30400768.12973310,0
20057,1653933600000,30706.85000000,30720.00000000,30643.04000000,30674.80000000,796.66290000,1653937199999,24446785.46288930,24386,359.77974000,11040589.17762490,0
20058,1653937200000,30674.79000000,30878.10000000,30586.27000000,30643.11000000,3952.95040000,1653940799999,121360020.10621850,39696,1052.25954000,32324274.07523370,0

#### save dataset to csv

In [4]:
btcDf.to_csv('bitcoin.csv',index=False)